language: python

python:
   - "3.5"

sudo: false

install:
    #Sal changed these from pip to pip3, hopefully didn't break anything?!
    - pip3 install --upgrade pip
    - pip3 --version
    - pip3 install coverage
    - pip3 install pylint
    - pip3 install Flask
    - pip3 install Flask-SQLAlchemy
    - pip3 install Flask-Testing
    - pip3 install requests
    - pip3 install autopep8

before_script:
    #also changed coverage to version 3
    - uname -a
    - printenv
    - pip list
    - coverage3 --version
    - pylint   --version

script:
    - date
    - ls -al
    - make test
