language: python

python:
   - "3.5"

sudo: false

install:
    - pip install --upgrade pip
    - pip --version
    - pip install coverage
    - pip install pylint
    - pip install Flask
    - pip install Flask-SQLAlchemy
    - pip install Flask-Testing

before_script:
    - uname -a
    - printenv
    - pip list
    - coverage --version
    - pylint   --version

script:
    - date
    - ls -al
    - make test
