FORMAT: 1A
HOST: downingjones.me
# Downing Jones API

The Downing Jones API allows for data requests on
stock market exchanges, companies, locations, and currencies.

# Downing Jones API Root [/api]
This resource does not have any attributes. Instead it offers the initial API affordances in the form of the links in the JSON body.

It is recommend to follow the “url” link values to retrieve resources.
## Retrieve Entry Points [GET]

+ Response 200 (application/json)

        {
            "company_url": "/company", 
            "currency_url": "/currency", 
            "exchange_url": "/exchange", 
            "location_url": "/location"
        }


## Group Stock Market Exchanges

Resources related to stock exchanges in the API.

## Exchange [/api/exchange/{exchange_id}]

A Exchange object has the following at tributes:

+ id
+ name
+ name_code
+ market_cap
+ location
+ currency

+ Parameters
    + id: 1 (required, number) - Name of the Exchange in form of a number (1-11)

### View an Exchange's Details [GET]


+ Response 200 (application/json)

        [
            {
              "currency": "CAD", 
              "id": 1, 
              "location": "Toronto, Canada", 
              "market_cap": "1,939 billion", 
              "name": "Toronto Stock Exchange", 
              "name_code": "TOR"
            }
        ]

## Group Companies

Resources related to companies in the API.

## Company [/api/company/{company_id}]

A Company object has the following attributes:

+ id
+ symbol
+ name
+ exchange
+ location
+ currency
+ open_price
+ previous_price
+ percent_change
+ year_high
+ ask_price
+ eps
+ peg
+ days_range
+ percent_change_fifty
+ percent_change_twohundred
+ volume
+ avg_volume
+ market_cap


+ Parameters
    + company_id: 1 (required, number) - Name of the Company in form of a number (1-1650)

### View a Company's Details [GET]

+ Response 200 (application/json)

        [
            {
                "ask_price": "0.270", 
                "avg_volume": "26811", 
                "days_range": "0.205 - 0.205", 
                "eps": "-0.320", 
                "exchange": "TOR", 
                "id": 1, 
                "location": "Toronto, Canada", 
                "market_cap": null, 
                "name": "RARE ELEMENT RESOURCES LTD", 
                "open_price": "0.205", 
                "peg": "0.000", 
                "percent_change": "+0.000%", 
                "percent_change_fifty": "-20.069%", 
                "percent_change_twohundred": "-50.749%", 
                "previous_price": "0.205", 
                "symbol": "RES.TO", 
                "volume": "500", 
                "year_high": "1.310"
            }          
        ]

## Group Locations

Resources related to location in the API.

## Location [/api/location/{location_id}]

A Location object has the following attributes:

+ id
+ name
+ iso
+ capital
+ GDP
+ currency
+ exchange

+ Parameters
    + location_id: 1 (required, number) - Name of the Location in form of a number (1-11)

### View a Location's Details [GET]

+ Response 200 (application/json)

        [
            {
                "GDP": "1.827 trillion USD", 
                "capital": "Ottawa", 
                "currency": "CAD", 
                "id": 1, 
                "iso": "CA", 
                "location": "Toronto Stock Exchange", 
                "name": "Toronto, Canada"
            }
        ]

## Group Currencies

Resources related to currencies in the API.

## Currency [/api/currency/{currency_id}]

A Currency object has the following attributes:

+ id
+ name
+ currency
+ locations
+ exchanges
+ exchange_rate

+ Parameters
    + currency_id: 1 (required, number) - Name of the Currency in form of a number (1-7)

### View a Currency's Details [GET]

+ Response 200 (application/json)

        [
            {
                "currency": "CAD", 
                "exchange_rate": 0.76, 
                "exchanges": "TOR", 
                "id": 1, 
                "locations": "Canada", 
                "name": "Canadian Dollar"
            }            
        ]
